[package]
name = "smart_gate"
edition = "2024"    # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
# world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "main" }
# TODO: This will be changed to use the mvr to automatically resolve the dependencies based on the chain. 
# For now, we resolve the dependencies locally for fast iteration.
world = { local = "../../../world-contracts/contracts/world" }


# Local net: use `sui move build -e local` / `sui client publish -e local` (chain ID changes each run)
[environments]
local = "0x0"


# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
[addresses]
smart_gate = "0x0"
