services:
  sui-local:
    build: .
    image: sui-docker
    stdin_open: true
    tty: true
    ports:
      # Exposes local Sui node RPC â€” for local development only
      - "9000:9000"
    environment:
      - SUI_NETWORK=local
    volumes:
      - sui-keystore:/root/.sui
      - ./workspace-data:/workspace/data
      - .:/workspace/docker
      - ../:/workspace/builder-scaffold
      - world-contracts:/workspace/world-contracts

volumes:
  sui-keystore:
  world-contracts:
